blank_issues_enabled: false
contact_links:
  - name: Issue Report
    url: https://github.com/ClaudiusMinimus/CreatePotatoUltimate/blob/main/.github/ISSUE_TEMPLATE/issue_report.yml
    about: Please complete the form to sumbit an issue report.
  - name: CM\'s World Discord
    url: https://discord.com/invite/jXrx4Tu
    about: Please join CM\'s World discord for support, questions, and more.
