[[curiosSettings]]
  identifier = "ring"
  size = 4
[[curiosSettings]]
  identifier = "charm"
  size = 4
[[curiosSettings]]
  identifier = "belt"
  size = 2
[[curiosSettings]]
  identifier = "head"
  size = 2
