	###########################################################################################################
	## General settings.
	###########################################################################################################
	["YUNG's Better Strongholds".General]
		# Allows strongholds to be slightly destroyed by small noodle caves.
		# Note that they will remain unaffected by large caverns.
		# Default: false
		"Enable Structure Ruin" = false
		# The chance for each End Portal Frame block to spawn already filled with an Eye of Ender.
		# Default: 0.1
		"Filled Portal Frame Chance" = 0.1
