#.
#Parameters and abilities of kinetic mechanisms
[kinetics]
	#.
	#.
	#Whether Deployer killed entities should drop experience.
	deployerKillDropXp = true
	#.
	#Scale for experience dropped from Deployer killed entities.
	# Default: 1.0
	# Range: 0.0 ~ 1.0
	deployerKillXpScale = 1.0
	#.
	#Whether Deployer mined blocks should drop experience.
	deployerMineDropXp = true
	#.
	#Scale for experience dropped from Deployer mined blocks.
	# Default: 1.0
	# Range: 0.0 ~ 1.0
	deployerMineXpScale = 1.0
	#.
	#Whether Deployer collect dropped experience as Experience Nugget.
	deployerCollectXp = true
	#.
	#Whether Mending enchantment applies to Deployer held item (Needs deployerCollectXp = true).
	deployerMendItem = true
	#.
	#Whether Deployer can perform sweep attack.
	deployerSweepAttack = true
	#.
	#Whether Crushing Wheel killed entities should drop experience.
	crushingWheelKillDropXp = true
	#.
	#Scale for experience dropped from Crushing Wheel killed entities.
	# Default: 0.3400000035762787
	# Range: 0.0 ~ 1.0
	crushingWheelKillDropXpScale = 0.3400000035762787
	#.
	#Probability of Crushing Wheel killed entities dropping experience.
	# Default: 0.30000001192092896
	# Range: 0.0 ~ 1.0
	crushingWheelKillDropXpChance = 0.30000001192092896

		#.
		#Fine tune the kinetic stats of individual components
		[kinetics.stressValues.v1]

			#.
			#.
			#[in Stress Units]
			#Configure the individual stress impact of mechanical blocks. Note that this cost is doubled for every speed increase it receives.
			[kinetics.stressValues.v1.impact]
				mechanical_grindstone = 4.0
				grindstone_drain = 4.0

	#.
	#Parameters and abilities of fluids and fluid operating components
	[kinetics.fluids]
		#.
		#.
		#Whether Liquid Experience vaporize into Experience Orbs upon placement.
		experienceVaporizeOnPlacement = true
		#.
		#The amount of liquid a Printer can hold (mB).
		#[@cui:RequiresReload:server]
		# Default: 4000
		# Range: > 1000
		printerFluidCapacity = 4000
		#.
		#Whether printing custom name (displayed in italic) as item name (displayed in non-italic).
		printingCustomNameAsItemName = false
		#.
		#The generation change when copy written books, value of 1 will prevent copying copy of copy
		# Default: -3
		# Range: -3 ~ 1
		printingGenerationChange = -3
		#.
		#The amount of liquid a Blaze Enchanter can hold (mB).
		#[@cui:RequiresReload:server]
		# Default: 4000
		# Range: > 1000
		blazeEnchanterFluidCapacity = 4000
		#.
		#The amount of liquid a Blaze Forger can hold (mB).
		#[@cui:RequiresReload:server]
		# Default: 4000
		# Range: > 1000
		blazeForgerFluidCapacity = 4000

	#.
	#Parameters and abilities of enchantment operating components
	[kinetics.enchantments]
		#.
		#.
		#The max experience level a Blaze Enchanter can use in Regular Enchanting
		# Default: 30
		# Range: > 0
		blazeEnchanterMaxEnchantLevel = 30
		#.
		#The max experience level a Blaze Enchanter can use in Super Enchanting
		# Default: 60
		# Range: > 0
		blazeEnchanterMaxSuperEnchantLevel = 60
		#.
		#Max enchantment level in Super Enchanting will be extended by this value
		# Default: 1
		# Range: 0 ~ 255
		enchantmentMaxLevelExtension = 1
		#.
		#If Super Enchanting and Super Forging ignores enchantment compatibility
		ignoreEnchantmentCompatibility = true

	#.
	#Parameters and abilities of processing mechanisms and appliances
	[kinetics.processing]
		#.
		#.
		#Probability of regular lightning strike transforming Block of Experience.
		# Default: 1.0
		# Range: 0.0 ~ 1.0
		regularLightningStrikeTransformXpBlockChance = 1.0
