!!dev.wuffs.squatgrow.config.SquatGrowConfig
allowAdventureTwerking: true
chance: 0.25
debug: false
enableMysticalCrops: true
ignoreList: ['minecraft:acacia_sapling', 'minecraft:spruce_sapling', 'minecraft:oak_sapling',
  'minecraft:jungle_sapling', 'minecraft:dark_oak_sapling', 'minecraft:birch_sapling',
  'minecraft:grass_block', 'minecraft:grass', 'minecraft:tall_grass', 'minecraft:netherrack',
  'minecraft:warped_nylium', 'minecraft:crimson_nylium']
range: 3
useWhitelist: false
