[recipes]
	#Removes the scaling repair cost of items in an anvil
	enableCheapAnvilRepair = true
	#Allows throwing things into specific fluids to convert them.
	#The built-in datapack includes recipes to convert Concrete Powder into Concrete, but this feature can be extended using Data Packs
	#See https://mods.oitsjustjose.com/V-Tweaks/#fluid-recipes for datapack documentation.
	enableFluidConversionRecipes = true
	#Allows use of datapacks to create NBT-strict anvil combination recipes. The built-in datapack does not add any recipes!
	#See https://mods.oitsjustjose.com/V-Tweaks/#anvil-recipes for datapack documentation.
	enableDataDrivenAnvilRecipes = true

[mixins]
	#If enabled, this tweak prevents cactus from destroying items that run into it
	enableCactusItemProtection = false
	#If enabled, allows splash potions of water to behave the same as throwing an item in water via V-Tweaks' Fluid Conversion Recipes
	enableSplashPotionTweak = true
	#If enabled, items entities will no longer stack together like Minecraft Beta
	enableNonStackingItemTweak = false
	#If enabled, nothing will be able to sink into Powdered Snow blocks anymore
	enableSolidPowderedSnow = false

[world]
	#Disables thunder storms, converting storms to normal rain
	enableStormTweak = false

	[world.peacefulsurface]
		#Peaceful Surface will only apply on nights whose moon phases are contained in this list (by default, all nights except for New Moons are going to be peaceful).
		#Options can include: FULL, WANING_GIBBOUS, LAST_QUARTER, WANING_CRESCENT, NEW, WAXING_CRESCENT, FIRST_QUARTER, WAXING_GIBBOUS
		moonPhasesToApplyTo = ["FULL", "WANING_GIBBOUS", "LAST_QUARTER", "WANING_CRESCENT", "WAXING_CRESCENT", "FIRST_QUARTER", "WAXING_GIBBOUS"]
		#Prevents mobs from spawning above the configured sea level on nights of the configured moon phases
		enabled = false
		#The configured 'sea level' which mobs will be prevented from spawning
		# Default: 60
		# Range: > -2147483648
		seaLevel = 60

[block]
	#Allows uneaten cake to drop itself when broken
	enableCakeDrop = true
	#Allows the player to re-light any block with the 'lit' blockstate when holding any #vtweaks:ignition_item (item tag). Blacklist blocks using the #vtweaks:torch_ignition_blacklist block tag.
	enableTorchLighting = true
	#Allows right-clicking crops when fully grown to harvest. Adding a block to the #vtweaks:blacklisted_harvest_crops block tag will prevent this tweak from applying to said crop.
	enableCropTweaks = true

	[block.chopdown]
		#Trees fall down using falling block entities
		enabled = false
		#The minimum number of logs above the one broken to be detected as a tree
		# Default: 3
		# Range: > 1
		numLogsRequired = 3
		#The radius used to attempt to find leaves to detect a tree. Set this to a large number to detect larger sparse trees (may cause lag)
		# Default: 64
		# Range: > 1
		leafSearchRadius = 64
		#If enabled, ChopDown will only work when the player is using the right tool for the log
		rightToolRequired = false

[entity]
	#Prevents pets from being hit by friendly fire.
	#OWNER prevents only the owner of the pet from hurting a pet, whereas ALL prevents any player from hurting any pet.
	#DISABLED disables the tweak.
	#Allowed Values: DISABLED, OWNER, ALL
	enablePetFriendlyFireTweak = "OWNER"
	#Allows any #vtweaks:clear_glass, or glow ink sac, to be activated on an item frame while sneaking to make the item frame transparent or glowing respectively.
	enableItemFrameTweak = true
	#When any #c:creepers explodes, all blocks destroyed will plop back into place after a few seconds
	ungriefCreepers = false
	#Allows use of datapacks to prevent a given types of entities from spawning in given biomes. The built-in datapack does not cull any entities.
	#See https://mods.oitsjustjose.com/V-Tweaks/#entity-culling for datapack documentation.
	enableDataDrivenEntityCulling = true

	[entity.challengers]
		#Enable colored particles for challenger mobs (respects the player's particle setting)
		enableParticles = true
		#A data-driven way to make some special mobs with abilities, effects, specialized loot and more!
		#See https://mods.oitsjustjose.com/V-Tweaks/#challengers for datapack documentation
		enabled = true
		#Controls the overall chance of attempting to convert a monster to a Challenger.
		#This chance is applied before any Challenger Mob weights or entity filters
		# Default: 0.25
		# Range: 0.0 ~ 1.0
		globalChance = 0.25

	[entity.featherplucking]
		#Allows feathers to be plucked from any #c:chickens using any #c:tools/shear
		enabled = true
		#Should baby #c:chickens be able to have feathers plucked from them?
		worksOnBabies = false
		#The amount of time (in Milliseconds) between plucks. Defaults to 10 minutes.
		# Default: 600000
		# Range: 1 ~ 9223372036854775807
		cooldownInMilliseconds = 600000

[player]
	#Feather Falling IV or above redirects all fall damage the player's boots
	enableFeatherFallTweak = true
	#Prevents drops from a player's death from de-spawning
	enablePlayerDeathDropSafety = false
