	[client.entity]
		#Makes Bee entities half-sized (does not affect their hit-box)
		enableSmallBees = true

	[client.tooltips]
		#Show tool durability on item hover
		#Allowed Values: NEVER, WITH_SHIFT, ALWAYS
		durabilityTooltipSetting = "WITH_SHIFT"
